steps:

  - id: "Rodando teste unitário"
    name: 'golang'
    env:
      - 'GOPATH=/workspace'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        mkdir -p src/github.com/lgdevlop/go-hpa/app;
        cp app/hpa.go src/github.com/lgdevlop/go-hpa/app;
        cp -r app/loop src/github.com/lgdevlop/go-hpa/app;
        go test ./...

  - id: "Criando imagem do Dockerfile"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA', '-f', '.docker/Dockerfile', '.']
  
  - id: "Subindo imagem"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA']

  - id: "Ajustando o arquivo de deploy k8s"
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#lgdevlop/go-hpa:1.0.0#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' k8s/k8s.yaml > k8s/k8s-new.yaml;
      cat k8s/k8s-new.yaml;

- id: "Fazendo o deploy do k8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/k8s-new.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CC_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CC_NAME}'
